// AGENT 1: PROSE QUALITY FIXES
// ================================
// Scenarios changed and why:
//
// 1 (II - The Forecast): Replaced cliché opening metaphor; tightened middle section
// 3 (IV - The Absurd Commute): Cut flabby clauses; sharpened the emotional beat
// 8 (IX - Four Thousand Weeks): MAJOR rewrite — most bloated scenario. Cut ~30%, varied sentence rhythm
// 9 (X - The Last Question): Tightened self-conscious meta-narration; made it land harder
// 10 (XI - Library of Babel): Cut excessive listing; sharpened the parental unease
// 11 (XII - The Untranslatable): Tightened ending; cut over-explanation of the gap
// 13 (XIV - The Circle): Cut wordy middle section; made the debt feel concrete not abstract
// 14 (XV - The Last Forest): Broke up marathon sentences; added sensory grounding
// 15 (XVI - The Immortality Pill): Major tightening — showed the weight of immortality instead of explaining it
// 19 (XX - The Inheritance Interview): Tightened; cut redundant business-speak
// 22 (XXIII - The Listening): Trimmed wordy setup; let the dadirri experience breathe
// 23 (XXIV - The Patent): Significant tightening — the IP law explanation was drowning the moral core
//
// NOT changed (already strong): 0, 2, 4, 5, 6, 7, 12, 16, 17, 18, 20, 21
// XXI vs XV overlap: Already resolved. XV = lithium mining, XXI = hydroelectric dam. Different resources,
// different community alternatives, different philosophical tensions. No rewrite needed.

const PROSE_FIXES = {

  1: `Your doctor calls on a Tuesday. Something in your bloodwork. Not fatal, not painful — but in one year you will lose your eyesight completely. Irreversibly. The rest of your life will be fine, the doctor assures you. Just <em>dark</em>. You have twelve months of seeing left. Twelve months to watch light move across a room at different hours, to memorize the faces of everyone you love, to read a book with your own eyes. The countdown started the moment the phone rang, whether you acknowledge it or not. Every morning you wake now is one morning closer to a horizon you cannot push back.`,

  3: `Three years into a PhD, you are halfway through a thesis on something you used to care about deeply enough to spend years in a library. Last month you read a paper that proves your central argument is wrong — not wrong in a way that can be patched, but structurally, irreparably wrong. You could pivot and lose two years. You could quit and leave with nothing. Or you could push through to completion, producing scholarship you no longer believe in, building on a foundation you know is cracked. Your supervisor says finish. This is normal. No thesis is perfect. But something in you keeps asking <em>why?</em> — and the answer is not coming.`,

  8: `You are twenty-eight when the offer arrives: lead a project that could reshape how education works in your country. The kind of systemic intervention that might give millions of children a better start. The work will consume five years. No weekends, no sustained hobbies, no long dinners that stretch past midnight. Your relationships will narrow to the functional. The texture of daily life will flatten into something instrumental and relentless. Meanwhile, your best friend just had a baby whose early years you will largely miss. Your parents are entering the stage of life where time with them has started to feel finite. You have been meaning to learn piano for a decade. You have roughly <em>four thousand weeks</em> on this earth. The question is not what to do with them but what to sacrifice — because every yes forecloses a dozen other lives you might have lived.`,

  9: `It's late, and you are alone with this. You have been making choices for the last several minutes that you already knew the answers to before you clicked — perhaps you have known them for years but never said them plainly enough to feel their weight. That is the thing about philosophy: it does not teach you what to think. It forces you to <em>admit</em> what you already believe, to look directly at the principles you have been living by without quite naming them. All of this has been a mirror. The question now is not whether the reflection is flattering but whether it is true — and whether you have the courage to sit with what it shows you.`,

  10: `Your child is twelve and has never had to memorize anything substantial. AI does their research, drafts their essays, checks their arithmetic. They are happy, curious, engaged with ideas in their own way — but when you ask them to explain <em>why</em> something is true, not just what the answer is, they shrug and say "the AI told me." Their school wants to ban the tools entirely. Other parents think this is absurd — no different from banning calculators in the 1980s. You find yourself uncertain whether either side has fully grasped what is at stake.`,

  11: `Your best friend's father died last year — someone you were close to as well. At the funeral you said all the things one is supposed to say. Quiet condolences, memories offered carefully, presence maintained with steady attention. Your friend thanked you afterward, told you it helped. You believed them. But last night, unguarded and several drinks past sober, they said something that has been sitting heavy in your chest ever since: <em>"You don't actually understand what this is like."</em> And they are right. You have never lost a parent, never stood in that particular valley. What you offered was compassion filtered through imagination rather than lived knowledge. You were performing empathy, and performing it well enough that it seemed real to both of you — but now the gap between your goodwill and their suffering feels unbridgeable, and you are not sure language was ever built to close it.`,

  13: `Your religious community — the one you grew up in, the one your parents still attend every week — has taken a public stance against something you believe in deeply. Not as a matter of preference. As a moral conviction you hold in your bones. They are wrong, and you know it in a way that does not admit doubt. But these are also the people who fed your family when you couldn't feed yourselves. Who showed up at your door during the worst year of your life without being asked. Who taught you what kindness looks like in practice rather than in principle. You owe them something that cannot be reduced to gratitude, a debt made of presence and care and showing up. And yet staying means endorsing — or at least being complicit in your silence while they do harm under the banner of the same tradition that once held you.`,

  14: `A mining company wants lithium from a valley in Bolivia — the kind that goes into batteries for electric cars, the technology that is supposed to save us from climate collapse. The valley is home to four hundred indigenous people who have lived there for centuries. Their relationship to the land is not ownership in any sense the company's lawyers would recognize. It is closer to kinship. They do not want to move. The company offers money, new housing, jobs in the mine. The community says <em>no</em> — not because the offer is inadequate, but because the premise is unacceptable. The government is considering eminent domain. The planet is warming. The carbon clock is ticking. Millions of lives hang in the balance of whether we decarbonize fast enough. Four hundred people will not move, and you are asked to weigh their home against the aggregate suffering of millions who might lose theirs.`,

  15: `A single injection. Gene therapy. Your telomeres stop shortening — the biological clock that counts down to your body's obsolescence, halted mid-tick. You could live for centuries, perhaps longer. The catch: it is irreversible. No exit clause. No way to change your mind when the weight of centuries becomes unbearable. You will watch everyone you love die. All of them. Again and again — a procession of endings that you alone carry forward. Every relationship will be temporary for you in a way it is not for them, every intimacy shadowed by the knowledge that you will be the one left standing. And the urgency that makes Tuesday mornings feel real, that animal awareness that time is running out — the thought <em>"I should call my mother"</em> that only works because you might not get another chance — that vanishes. There is always tomorrow. And the day after that. And a thousand years of days after that.`,

  19: `The email arrives on a Tuesday morning: "Partner Track — Final Interview." Five years of work, distilled into a subject line. But you didn't build this alone. Your business partner — college roommate, first believer, the person who took a salary cut when the company was a fever dream and a maxed-out credit card — will be pushed out if you take this role. The fund wants you. Not both of you. They see your partner as "operational overhead." You know that's wrong. Every breakthrough was shared. Every crisis, they held the ship steady while you played the face. Your grandmother's phrase echoes: <em>umuntu ngumuntu ngabantu</em> — a person is a person through other people. The success they want to invest in was never yours alone. But the world doesn't reward partnerships the way it rewards individuals.`,

  22: `You are an environmental scientist assessing whether a patch of old-growth forest should be cleared for affordable housing. Three weeks of data — soil samples, biodiversity indexes, carbon sequestration rates, water table measurements — all pointing toward the same conclusion: the forest can be sustainably cleared if certain mitigation measures are followed. The numbers are solid. Your methodology is peer-reviewed. Then the local Aboriginal elder asks if you would sit with her in the forest for a morning before you write your report. You almost say no. You have deadlines, and sitting isn't data collection. But something in how she asks makes you say yes. She doesn't lecture you or argue with your findings. She sits. After a while you begin to hear things your instruments didn't measure: the particular quality of silence between birdcalls, the way light moves through the canopy in patterns that suggest relationships between species your survey never captured. A feeling — unscientific, unmeasurable, but unmistakable — that the forest is not a collection of organisms but a <em>presence</em>. She calls this dadirri. Deep listening. The kind that requires you to be quiet long enough for the land itself to speak.`,

  23: `A decade ago, during ethnobotanical fieldwork, an elder showed you a plant preparation her grandmother had taught her, passed down through a chain of knowledge stretching back further than anyone could trace. She shared it freely — not as transaction but as relationship, carrying with it the obligation of reciprocity and the understanding that gifts must keep moving. You published your findings with attribution and consent. A pharmaceutical company read your paper, synthesized the active compound, and developed a treatment now helping hundreds of thousands of people. The company is filing a patent. They have offered you a consultancy fee and co-inventor credit. The elder and her community have been offered nothing. Traditional knowledge, in the eyes of patent law, belongs to no one — the community's knowledge entered the public domain the moment you published it. You understand the legal logic. You also understand it rests on a foundation the elder would find incomprehensible: that knowledge can be owned, that sharing it freely means losing it, that the gift economy is just the commons waiting to be enclosed.`,

};
